### ISSUE TITLE
 rozliczenie: użytkownik o roli volunteer nie może wejść do edycji puszki jeśli

### ISSUE THREAD

**Issue by Safeheaded** [akai-org/wosp-puszki#199]
rozliczenie: użytkownik o roli volunteer nie może wejść do edycji puszki jeśli is_given_to_collector=true &&  given_to_collector_user_id != authUser.id

Ma się pojawić wtedy komunikat: Puszka jest już liczona przez kogoś innego

**Comment by Cheriit** [comment]
Uwaga - backend zwraca informacje o błędzie ale nie jest ona wyświetlana
