### ISSUE TITLE
Przejrzenie logiki websocketów i sprawdzenie, czy jest możliwość ich uproszczenia

### ISSUE THREAD

**Issue by Cheriit** [akai-org/wosp-puszki#20]

**Comment by marcinlawnik** [comment]
Powstał nowy system oparty o htttp i cache, nowy frontend z niego korzysta.
Stary frontend trzebaby przepiąć na tenże system, albo zlikwidować stary frontend od wyświetlania ilości zebranej kasy.

**Comment by marcinlawnik** [comment]
Wywaliłem wszystko co związane z WS.
https://github.com/akai-org/wosp-puszki/commit/09c79e07c26c65773e344578c2dcf05d91424dca
